name: openvector_client
description: OpenVector — cross-platform air traffic control client.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
